services:
  # 1. FastAPI Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: backend_api
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # 2. MLflow Service
  mlflow:
    image: python:3.10-slim
    container_name: mlflow_server
    command: >
      bash -c "pip install mlflow boto3 &&
               mlflow server
               --host 0.0.0.0
               --port 5000
               --default-artifact-root /mlruns"
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/mlruns
  
  # 3. Streamlit Frontend Dashboard
  frontend:
    build:
      context: ./frontend
    container_name: frontend_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_API_URL=http://backend:8000
    depends_on:
      - backend

# Defines a default network for all services to communicate
networks:
  default:
    driver: bridge