version: '3.8'
services:
  mlflow:
    image: python:3.9-slim
    container_name: mlflow1_server
    command: >
      bash -c "pip install mlflow boto3 &&
               mlflow server --host 0.0.0.0 --port 5000
               --default-artifact-root /mlruns"
    ports:
      - "5000:5000"
    volumes:
      -./mlflow_data:/mlruns